---
- name: 'Configure apt-listchanges: disable confirmation'
  debconf:
      name: apt-listchanges
      question: apt-listchanges/confirm
      vtype: boolean
      value: 'false'
  register: apt_listchanges_confirm

- name: 'Configure apt-listchanges: mail root'
  debconf:
      name: apt-listchanges
      question: apt-listchanges/email-address
      vtype: string
      value: root
  register: apt_listchanges_mail

- name: 'Configure apt-listchanges: output to mail only'
  debconf:
      name: apt-listchanges
      question: apt-listchanges/frontend
      vtype: select
      value: mail
  register: apt_listchanges_frontend

- name: 'Configure apt-listchanges: output both changelogs and news'
  debconf:
      name: apt-listchanges
      question: apt-listchanges/which
      vtype: select
      value: both
  register: apt_listchanges_which

- name: 'Install apt-listchanges'
  apt:
      name:
          - apt-listchanges
      state: latest
  register: apt_listchanges_inst

- name: 'Apply configuration changes to existing apt-listchanges installation'
  command:
      cmd: 'dpkg-reconfigure --unseen-only -pcritical apt-listchanges'
  when:
      - not apt_listchanges_inst.changed
      - apt_listchanges_confirm.changed or apt_listchanges_mail.changed or apt_listchanges_frontend.changed or apt_listchanges_which.changed
