# When we stop wanting a user/key, we shouldn't just remove them from this file;
# we should leave them here but with `state: absent` so they get tidied away.
---
- name: 'Create deploy user'
  user:
      name: 'deploy'
      comment: 'SRCF deployment'
      group: 'deploy'
      groups:
          - adm
          - cdrom
          - sudo
          - dip
          - plugdev
          - lxd
          - lpadmin
          - sambashare
      shell: '/bin/bash'

- name: 'Update deploy user SSH keys'
  authorized_key:
      user: deploy
      key: '{{ item }}'
  with_items:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyIux3HSv59gPrHF7qJstuuC36Q7opIvk9A1PZ4O73RJ6yUDuB2AIoiH9t/TlojNFVDWHZWkFMOBKNeaMbJMK5T3GndkTObD5Jt1Pg0dalkuLfSghTQYY/IXYMnUIMmZxxp1Wau0D+ish01r0MCFTj0sHQh/d/ZU2oLkmI0p2nWNNM4t0k+OJOt/vXwQomazvEvgt8pg/04jyEW1H7AkMO2ekikJHphMj5IOu0qw3RRqARKXV0EBTyMkdOpxdkpaWLQE5yK6oB3g3R3fOUK0F/LRWfwuZS2P8ucd518nvPvrQSER2+R7UFxm5/Z/lgQGvG5MUHwrRsgY+O5JviPOJeQ== root@pip'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt0ODUvgyVT+1vOPlpyjvkMf0c5BiHnfYTY7HA7zlPp0cO1TBtMUCqNDb67K4UwC3jQPxeQ1IlM8IuSfS4k4VoQdkXHk0lIhpXRSsYxPvr+kbUZsdk/IVwnz68aT6jpt9AK+5GoRjCJoz6sC/IyeYonR2+oDo44A3h1AvXW+ZBUFG4f8cOdmjPw71OJ2YO5meLmN/wNOdbtFYoUeSp9ZhYUU4b7KOMHkmbNeyYRs8ZCUmx162VeeiluuHeNplqPHjabePKWNI6mZMpdkiMLZcs9qz8k7ayOo+mMoVb6SgK2ubBhZ6ahL9aLoyZtH8hX0BDC0/7PO3TtUxLRuOlQat1 mas90-YubiKey-201902'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChkOFccWTJjT5f2K11b4il5tiAp0125naAVP1CSemZgR1xYkiXtRJIpflnJ2CKZI+aHDsxiHt9qUtsFSeHqgmHC1pgXF8IrUSsMe0AQGjjVXB9EScDoOGug2l0iA4cvN1tYDUpJwt1B5s7XJlNefO1CHCsMtsV2qbCTpPKkgWx6ScaqPCXkKFuCkzQAbihpA6uVTkjKXnaJT0I1DGJLOqOPw+IzO13G/yWFpSshZwoMwNDKMWyxCqSn5IrrHzawizdUTfGukKcubhxOqTBnB5mYZyRWHb85Cu81gZmZ5u8Z0lbgR2r89bLyj6pSg8X6xhsLu7SCuTpxzjWW7JlbZSh mas90-YubiKey-Neo-cardno:000604876729'
