---
- name: 'Clean MOTD'
  file:
      path: "/etc/update-motd.d/{{ item }}"
      state: absent
  with_items:
      - '10-help-text'
      - '50-motd-news'
      - '80-esm'
      - '80-livepatch'

- name: 'Disable motd-news'
  systemd:
      name: 'motd-news'
      enabled: no
      masked: yes
