# When we stop wanting a user/key, we shouldn't just remove them from sysadmins/;
# we should leave them here but with `state: absent` so they get tidied away.
---
- name: 'Iterate through sysadmins'
  include_tasks: '{{ item }}'
  with_fileglob: '../sysadmins/*.yml'
