#SPDX-License-Identifier: MIT
---
# vars file for xcpng_host

_xcpng_base_install_packages:
  - ncurses-term
  - munin-node
  - perl-Net-CIDR
  - smartmontools
  - lm_sensors

_xcpng_nagios_packages:
  - nrpe
  - nagios-plugins-disk
  - nagios-plugins-load

_xcpng_all_install_packages:
  "{{ _xcpng_base_install_packages +
      (_xcpng_nagios_packages if xcpng_install_nagios_nrpe else []) +
      xcpng_extra_packages
   }}"
