name: Lint Ansible

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Lint requirements
        uses: ansible-community/ansible-lint-action@v6.2.1
        with:
          path: "requirements.yml"

      - name: Lint roles
        uses: ansible-community/ansible-lint-action@v6.2.1
        with:
          path: "roles/"
